apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
    spec:
      containers:
      - image: 879772956301.dkr.ecr.ap-southeast-1.amazonaws.com/user09-gateway:v1
        name: gateway
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 400m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 1000Mi