apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: taxi
  namespace: taxi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taxi
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 5