server:
  port: 8088
---
spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: taxi
          uri: http://localhost:8081
          predicates:
            - Path=/taxis/**
        - id: passenger
          uri: http://localhost:8082
          predicates:
            - Path=/passengers/**
        - id: call
          uri: http://localhost:8083
          predicates:
            - Path=/calls/**
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
logging.level: debug
---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: taxi
          uri: http://aaf28b2a102794e32acc6c2a2418fa43-123529799.ap-southeast-1.elb.amazonaws.com:8080
          predicates:
            - Path=/taxis/**
        - id: passenger
          uri: http://aaf28b2a102794e32acc6c2a2418fa43-123529799.ap-southeast-1.elb.amazonaws.com:8080
          predicates:
            - Path=/passengers/**
        - id: call
          uri: http://aaf28b2a102794e32acc6c2a2418fa43-123529799.ap-southeast-1.elb.amazonaws.com:8080
          predicates:
            - Path=/calls/**
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
