server:
  port: 8080
---
spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: taxi
          destination: taxi
          contentType: application/json
        event-out:
          destination: taxi
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: info
feign:
  client:
    url:
      callUrl: http://localhost:8083
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 610
server:
  port: 8081
---
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${taxiKafka}
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: taxi
          destination: taxis
          contentType: application/json
        event-out:
          destination: taxis
          contentType: application/json
feign:
  client:
    url:
      callUrl: http://call:8080
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 610
