apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi
  labels:
    app: taxi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxi
  template:
    metadata:
      labels:
        app: taxi
    spec:
      containers:
        - name: taxi
          image: 090702195051.dkr.ecr.us-east-2.amazonaws.com/taxi:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5