apiVersion: apps/v1
kind: Deployment
metadata:
  name: texi
  labels:
    app: texi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: texi
  template:
    metadata:
      labels:
        app: texi
    spec:
      containers:
        - name: texi
          image: username/texi:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5