apiVersion: apps/v1
kind: Deployment
metadata:
  name: passenger
  labels:
    app: passenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passenger
  template:
    metadata:
      labels:
        app: passenger
    spec:
      containers:
        - name: passenger
          image: 879772956301.dkr.ecr.ap-southeast-1.amazonaws.com/user09-passenger:v1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 400m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 1000Mi
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5