server:
  port: 8080
---
spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: texi
          destination: texi
          contentType: application/json
        event-out:
          destination: texi
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: info
feign:
  client:
    url:
      callUrl: http://localhost:8083
server:
  port: 8081
---
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: texi
          destination: texi
          contentType: application/json
        event-out:
          destination: texi
          contentType: application/json
feign:
  client:
    url:
      callUrl: http://localhost:8083
